# <font color='orange'>Python Fundamentos - NumPy</font>

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

## NumPy
<details>
    <summary>
        <a class="btnfire small stroke"><em class="fas fa-chevron-circle-down"></em>&nbsp;&nbsp;Clique para mais detalhes</a>
    </summary>
    <br>
   
NumPy é um pacote para computação científica em Python. <br>
É uma biblioteca Python que fornece um objeto do tipo array. <br>
Um array pode ter uma ou várias dimensões (vetores ou matrizes). <br>
No núcleo do pacote NumPy, está o objeto ndarray. <br>
Existem algumas diferenças importantes entre as matrizes NumPy e as sequências Python padrão: <br>

- O array NumPy é criado com um tamanho fixo, ao contrário das listas Python, que podem crescer dinamicamente. Alterar o tamanho de um ndarray criará um novo array e excluirá o original. <br>
- Os elementos em um array NumPy devem ser todos do mesmo tipo de dado e, portanto, terão o mesmo tamanho na memória. Um objeto do tipo lista pode ter elementos de qualquer tipo de dado. <br>
- Os arrays NumPy facilitam operações matemáticas avançadas e outros tipos de operações em um grande número de dados. Normalmente, essas operações são executadas de forma mais eficiente, mais rápida e com menos código do que quando utilizando objetos do tipo lista. 

</details>

In [1]:
# Importando o pacote NumPy
import numpy as np

### Criando Arrays
É possível criar um array a partir de uma lista ou uma tupla usando o método array.

In [2]:
# Criando um array com uma dimensão (com um axis) a partir de uma lista
vetor1 = np.array([2, 3, 4, 5, 6, 7, 8, 9])
vetor1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Criando um array com uma dimensão (com um axis) a partir de uma tupla
vetor2 = np.array((10, 11, 12, 13, 14, 15, 16, 17, 18))
vetor2

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [4]:
# Criando um array com duas dimensões (com dois axes) sendo 2 linhas e 3 colunas utilizando uma lista de listas
# Cada lista é uma linha da matriz e a quantidade de elementos de uma lista, define o número de colunas
# O primeiro axis (linhas) tem tamanho 2
# O segundo axis (colunas) tem tamanho 3
matriz1 = np.array([[10, 20, 30], [40, 50, 60]])
matriz1

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
# Criando um array com duas dimensões (com dois axes) sendo 3 linhas e 2 colunas utilizando uma lista de tuplas
# Cada tupla é uma linha e a quantidade de elementos das tuplas é o número de colunas.
# O primeiro axis (linhas) tem tamanho 3
# O segundo axis (colunas) tem tamanho 2
matriz2 = np.array([(15, 25), (35, 45), (55, 65)])
matriz2

array([[15, 25],
       [35, 45],
       [55, 65]])

In [6]:
# Verificando o tipo de dado
type(matriz2)

numpy.ndarray

### Slicing
Os arrays com uma dimensão podem ser indexados e fatiados de maneira muito semelhante às listas e outras sequências Python. <br>
Arrays multidimensionais possuem um índice por dimensão

In [7]:
# Imprimindo o array
vetor1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Recuperando o primeiro elemento do array
vetor1[0]

2

In [9]:
# Recuperando os elementos da posição 0 até a posição 3
vetor1[0:3]

array([2, 3, 4])

In [10]:
# Imprimindo o array
matriz1

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
# Recuperando o elemento que está na primeira linha e na primeira coluna
matriz1[0, 0]

10

In [12]:
# Recuperando o elemento que está na segunda linha e na terceira coluna
matriz1[1, 2]

60

In [13]:
# Alterando o elemento que está na primeira linha e segunda coluna
matriz1[0, 1] = 88
matriz1

array([[10, 88, 30],
       [40, 50, 60]])

In [14]:
# Imprimindo o array
matriz2

array([[15, 25],
       [35, 45],
       [55, 65]])

In [15]:
# Recuperando as linhas 0, 1 e 2 da primeira coluna
matriz2[0:3, 0]

array([15, 35, 55])

In [16]:
# Imprimindo o array
matriz1

array([[10, 88, 30],
       [40, 50, 60]])

In [17]:
# Recuperando todas as linhas da segunda e terceira coluna.
# O número ao lado direito do sinal de dois pontos é exclusivo
matriz1[:, 1:3]

array([[88, 30],
       [50, 60]])

### Métodos e atributos de um array

In [18]:
# Verificando a quantidade de dimensões de um array
vetor2.ndim

1

In [19]:
# Verificando a quantidade de dimensões de um array
matriz1.ndim

2

In [20]:
# Imprimindo um array
vetor2

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [21]:
# Verificando o formato de um array - retorna a quantidade de elementos na dimensão
vetor2.shape

(9,)

In [22]:
# Imprimindo um array
matriz1

array([[10, 88, 30],
       [40, 50, 60]])

In [23]:
# Verificando o formato de um array - lembrando que a sequencia das dimensões são:
# 1º linha | 2º coluna e por ai vai
matriz1.shape

(2, 3)

In [24]:
# Imprimindo um array
matriz2

array([[15, 25],
       [35, 45],
       [55, 65]])

In [25]:
# Verificando o formato de um array
matriz2.shape

(3, 2)

In [26]:
# Verificando o tipo de dado dos elementos de um array
matriz2.dtype

dtype('int32')

In [27]:
# Retorna a quantidade de elementos de um array
matriz2.size

6

In [28]:
# Retorna a soma dos elementos de um array
matriz2.sum()

240

In [29]:
# Imprimindo um array
matriz1

array([[10, 88, 30],
       [40, 50, 60]])

In [32]:
# Retorna a soma de cada COLUNA
matriz1.sum(axis=0)    # sum(axis=0) - soma os elementos da COLUNA | por algum motivo quando ta no método o 0 vira coluna e o 1 vira linha

array([ 50, 138,  90])

In [33]:
# Retorna a soma de cada LINHA
matriz1.sum(axis=1)    # sum(axis=1) - soma os elementos da LINHA | por algum motivo quando ta no método o 0 vira coluna e o 1 vira linha

array([128, 150])

In [34]:
# Imprimindo um array
vetor2

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [35]:
# Retorna a soma acumulada dos elementos de um array
vetor2.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126], dtype=int32)

In [36]:
# Retorna a média dos elementos de um array
vetor2.mean()

14.0

In [37]:
# Retorna a mediana dos elementos de um array
np.median(vetor2)

14.0

In [38]:
# Retorna a variância dos elementos de um array.
# A variância indica a distância que os valores se encontram em relação à média. 
vetor2.var()

6.666666666666667

In [39]:
# Retorna o desvio padrão dos elementos de um array.
# O desvio padrão é a raiz quadrada da variância
vetor2.std()

2.581988897471611

In [40]:
# Retornando o valor máximo e mínimo dos elementos de um array
print("O maior valor é", vetor2.max(), "e o menor valor é", vetor2.min())

O maior valor é 18 e o menor valor é 10


In [41]:
# Criando um array com valores sequenciais. Parecido com a função buil-in range
# [start: end: step]
vetor3 = np.arange(2, 20, 2)
vetor3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
# Criando um array com valores sequenciais.
vetor4 = np.arange(10)
vetor4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
# Criando um array de duas dimensões com valores sequenciais.
matriz3 = np.arange(12).reshape(3, 4)
matriz3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
# Mudando formato do array
matriz3.reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [47]:
# Mudando formato do array informando apenas a quantidade de linhas
matriz3.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [48]:
# Mudando formato do array informando apenas a quantidade de colunas
matriz3.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
# Converte uma matriz em um vetor
matriz3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
# Criando um vetor com números aleatórios
# [start: end: size] = [começo, fim, quant valores gerados]
vetor5 = np.random.randint(5, 100, size=8)
vetor5

array([ 9, 41, 56, 32, 36,  7, 73, 43])

In [51]:
# Criando um array de duas dimensões com valores aleatórios.
matriz4 = np.random.randint(1, 1000, size=15).reshape(5, 3) # o resultado da multiplicação de reshape tem q ser = a size
matriz4

array([[822, 958, 240],
       [423, 332, 997],
       [815, 783, 669],
       [ 13, 159,  80],
       [303, 540, 474]])

In [52]:
# Criando um vetor especificando a quantidade de elementos dentro de um intervalo.
# O último elemento é inclusivo.
# esse método tem a caracteristica de colocar o primeiro e o ultimo elemento dentro do vetor
vetor6 = np.linspace(1, 100, 20)
vetor6

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [53]:
# Criando uma matriz de zeros
matrizZeros = np.zeros((4, 6))
matrizZeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [54]:
# Criando uma matriz com todos os elementos iguais a 1
matrizUm = np.ones([4, 4])
matrizUm

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
# Contar valores únicos no array NumPy
np.unique(matrizZeros, return_counts=True)

(array([0.]), array([24], dtype=int64))

In [56]:
# Imprimindo uma variável
matriz2

array([[15, 25],
       [35, 45],
       [55, 65]])

In [57]:
# Inserindo uma nova linha na matriz
matriz2 = np.append(matriz2, [[1,2]], axis=0)
matriz2

array([[15, 25],
       [35, 45],
       [55, 65],
       [ 1,  2]])

In [58]:
# Inserindo uma nova coluna na matriz
matriz2 = np.append(matriz2, [[1],[2],[3], [4]], axis=1)
matriz2

array([[15, 25,  1],
       [35, 45,  2],
       [55, 65,  3],
       [ 1,  2,  4]])

### Operações básicas

In [59]:
# Criando dois arrays com uma dimensão
v1 = np.array([20, 30, 40, 50])
v2 = np.arange(4)
print(v1)
print(v2)

[20 30 40 50]
[0 1 2 3]


In [60]:
# Somando os arrays
v1 + v2

array([20, 31, 42, 53])

In [61]:
# Subtraindo os arrays
v1 - v2

array([20, 29, 38, 47])

In [62]:
# Comparando arrays
v1 == v2

array([False, False, False, False])

In [63]:
# Elevando cada elemento a uma determinada potência
v2**2

array([0, 1, 4, 9], dtype=int32)

In [64]:
# Multiplicando elementos de dois arrays
v1 * v2

array([  0,  30,  80, 150])

In [65]:
# Criando matrizes
m1 = np.array([[5, 2],
               [0, 1]])
m2 = np.array([[2, 0],
               [3, 4]])

In [66]:
# Multiplicação de matrizes
m1.dot(m2)

array([[16,  8],
       [ 3,  4]])

### Exercícios

1 - Faça uma função chamada gera matriz que recebe como parâmetros de entrada (a, b, c, m) e que
tem como retorno um array Numpy de formato m × m (matriz quadrada), onde os elementos são os c
números igualmente espaçados obtidos ao se dividir o intervalo [a, b]. Caso não seja
possível construir tal array, a função deve retornar a mensagem "Não é possível
construir a matriz".


In [68]:
import numpy as np

def geraMatriz1(a, b, c, m):
    
    '''
    tradução dos parâmetros:
    a = onde começa
    b = onde termina (se eu nao me engano é exclusivo)
    c = quantidade de elementos (q tem q ser igual ao resultado da * do nº das linhas X o nº das colunas)
    m = nº de linhas/colunas (aqui ele ta fazendo a msm quantidade de linhas e de colunas)
    '''
    
    
    if(m * m == c):    # o resultado da multiplicação do número de linhas pelo número de colunas deve ser igual a quantidade de elementos
        return np.random.randint(a, b, size=c).reshape(m, m)
    else:
        print('Não é possível construir a matriz')

In [70]:
geraMatriz1(0, 10, 16, 4)

array([[9, 9, 5, 3],
       [8, 6, 0, 6],
       [9, 2, 0, 8],
       [8, 8, 6, 6]])

In [71]:
geraMatriz1(0, 10, 20, 4)

Não é possível construir a matriz


In [ ]:
# --------------------------------------------------------------------------------------------------------------- #

In [2]:
# Importando o pacote NumPy
import numpy as np

In [3]:
# Definindo a função
def geraMatriz1(a, b, c, m):
    if (m * m == c):
        return np.random.randint(a, b, size=c).reshape(m, m)
    else:
        print("Não é possível construir a matriz")

In [4]:
# Chamando a função
geraMatriz1(0, 10, 16, 4)

array([[1, 7, 7, 8],
       [2, 7, 8, 7],
       [0, 6, 7, 3],
       [6, 2, 6, 5]])

In [5]:
# Chamando a função
geraMatriz1(0, 10, 20, 4)

Não é possível construir a matriz


### Tratamento de Exceções
Uma exceção ocorre quando o código está sendo executado.<br>
O código está sintaticamente correto, mas apresenta erro durante a execução.

In [74]:
# Não é possível criar uma matriz com uma quantidade de elementos que não cabe no seu formato
np.random.randint(0, 10, size=20).reshape(4, 4)

ValueError: cannot reshape array of size 20 into shape (4,4)

In [75]:
# Definindo a função
def geraMatriz2(a, b, c, m):
    try:
        return np.random.randint(a, b, size=c).reshape(m, m)
    except ValueError as mensagemValueError: # Erro de valor
        print(mensagemValueError)
    except IOError as mensagemIOError: # Erro de entrada e saída
        print(mensagemIOError)
    except ZeroDivisionError as mensagemZeroDivisionError: # divisão por zero
        print(mensagemZeroDivisionError)
    except NameError as mensagemNameError: # variável não foi definida: 
        print(mensagemNameError)
    else:
        print("Não é possível criar a matriz")

In [81]:
# Chamando a função
geraMatriz2(1, 100, 20, 4)

cannot reshape array of size 20 into shape (4,4)


2 - Modifique a função do exercício anterior para imprimir:<br>
- a matriz criada; <br>
- a média e o desvio padrão das linhas; <br>
- a média e desvio padrão das colunas.

In [86]:
# Definindo a função
def geraMatriz3(a, b, c, m):
    np.random.seed(5)    # garante q os nº gerados sejam sempre os msms
    try:
        matriz = np.random.randint(a, b, size=c).reshape(m, m)
        print(matriz)
        print("Média das linhas:", matriz.mean(axis=1)) # calcula usando as colunas (axis=1)
        print("Desvio padrão das linhas:", matriz.std(axis=1)) # calcula usando as colunas (axis=1)
        print("Média das colunas:", matriz.mean(axis=0)) # calcula usando as linhas (axis=0)
        print("Desvio padrão das colunas:", matriz.std(axis=0)) # calcula usando as linhas (axis=0)
    except ValueError as mensagemValueError:
        print(mensagemValueError)

In [87]:
# Chamando a função
geraMatriz3(1, 100, 16, 4)

[[79 62 17 74]
 [ 9 63 28 31]
 [81  8 77 16]
 [54 81 28 45]]
Média das linhas: [58.   32.75 45.5  52.  ]
Desvio padrão das linhas: [24.46425965 19.39555361 33.64892272 19.17028951]
Média das colunas: [55.75 53.5  37.5  41.5 ]
Desvio padrão das colunas: [29.01185103 27.33587387 23.2432786  21.38340478]


3 - Modifique a função do exercício anterior para retornar uma matriz com a média e o desvio padrão das linhas e colunas.

In [90]:
# Definindo a função
def geraMatriz4(a, b, c, m):
    np.random.seed(5)
    try:
        matriz = np.random.randint(a, b, size=c).reshape(m, m)
        print(matriz)
        print("Média das linhas:", matriz.mean(axis=1))
        print("Desvio padrão das linhas:", matriz.std(axis=1))
        print("Média das colunas:", matriz.mean(axis=0))
        print("Desvio padrão das colunas:", matriz.std(axis=0))
        
        return np.array([(matriz.mean(axis=1)), (matriz.std(axis=1)), (matriz.mean(axis=0)), (matriz.std(axis=0))])
    except ValueError as mensagemValueError:
        print(mensagemValueError)

In [93]:
# Chamando a função
geraMatriz4(1, 100, 25, 5)

[[79 62 17 74  9]
 [63 28 31 81  8]
 [77 16 54 81 28]
 [45 78 76 66 48]
 [31 85 87 19 10]]
Média das linhas: [48.2 42.2 51.2 62.6 46.4]
Desvio padrão das linhas: [29.37618083 26.20992179 25.84105261 13.79275172 33.01878253]
Média das colunas: [59.  53.8 53.  64.2 20.6]
Desvio padrão das colunas: [18.54723699 27.27929618 26.32869157 23.26714422 15.56406117]


array([[48.2       , 42.2       , 51.2       , 62.6       , 46.4       ],
       [29.37618083, 26.20992179, 25.84105261, 13.79275172, 33.01878253],
       [59.        , 53.8       , 53.        , 64.2       , 20.6       ],
       [18.54723699, 27.27929618, 26.32869157, 23.26714422, 15.56406117]])

4 - Utilize a função do exercício anterior para gerar uma matriz. A partir dessa matriz gerada, utilize o conceito de fatiamento para criar uma nova matriz com os valores das duas últimas colunas.

In [13]:
# Chamando a função
m = geraMatriz4(1, 100, 25, 5)
m

[[79 62 17 74  9]
 [63 28 31 81  8]
 [77 16 54 81 28]
 [45 78 76 66 48]
 [31 85 87 19 10]]
Média das linhas: [48.2 42.2 51.2 62.6 46.4]
Desvio padrão das linhas: [29.37618083 26.20992179 25.84105261 13.79275172 33.01878253]
Média das colunas: [59.  53.8 53.  64.2 20.6]
Desvio padrão das colunas: [18.54723699 27.27929618 26.32869157 23.26714422 15.56406117]


array([[48.2       , 42.2       , 51.2       , 62.6       , 46.4       ],
       [29.37618083, 26.20992179, 25.84105261, 13.79275172, 33.01878253],
       [59.        , 53.8       , 53.        , 64.2       , 20.6       ],
       [18.54723699, 27.27929618, 26.32869157, 23.26714422, 15.56406117]])

In [14]:
# Criando uma nova matriz utilizando fatiamento
m2 = m[:, 3:5]
m2

array([[62.6       , 46.4       ],
       [13.79275172, 33.01878253],
       [64.2       , 20.6       ],
       [23.26714422, 15.56406117]])